name: 'Pull Request Comment Trigger'
description: 'Look for a "trigger word" in a pull-request description or comment, so that later steps can know whether or not to run.'
inputs:
  trigger:
    description: 'The string regexp to look for in pull-request descriptions and comments. For example "CH[[123]]"'
    required: true
outputs:
  triggered:
    description: the string 'true' if the trigger was found, otherwise the string 'false'
  trigger_var:
    description: The comment body.
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: check-circle
  color: red